site/Mastercard.MarketingCenter.Cms/Controllers/ListController.cs
using Mastercard.MarketingCenter.Cms.Core.ActionFilters;
using Mastercard.MarketingCenter.Cms.Core.DataTables;
using Mastercard.MarketingCenter.Cms.Core.Extensions;
using Mastercard.MarketingCenter.Cms.Models;
using Mastercard.MarketingCenter.Cms.Models.List;
using Mastercard.MarketingCenter.Cms.Services.Core;
using Mastercard.MarketingCenter.Cms.Services.Services;
using Mastercard.MarketingCenter.Common.Extensions;
using Mastercard.MarketingCenter.Data;
using Mastercard.MarketingCenter.Data.Daos;
using Mastercard.MarketingCenter.Data.Entities;
using Mastercard.MarketingCenter.Data.Entities.CustomSettings;
using Mastercard.MarketingCenter.Services;
using Mastercard.MarketingCenter.Services.Exceptions;
using Mastercard.MarketingCenter.Services.Extensions;
using Mastercard.MarketingCenter.Services.Interfaces;
using Pulsus;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace Mastercard.MarketingCenter.Cms.Controllers
{
    public class ListController : CmsBaseController
    {
        private readonly ListDao _listDao;
        private readonly ContentService _contentService;
        private readonly ListItemTrackingServices _listItemTrackingServices;
        private readonly IIssuerService _issuerService;
        private readonly UserContext _userContext;
        private readonly IAuthorizationService _authorizationService;
        private readonly ICalendarService _calendarService;
        private readonly IErrorMessageService _errorMessageService;
        private readonly IUrlService _urlService;

        public ListController(
            ListDao listDao,
            ContentService contentService,
            ListItemTrackingServices listItemTrackingServices,
            IIssuerService issuerService,
            UserContext userContext,
            IAuthorizationService authorizationService,
            ICalendarService calendarService,
            IErrorMessageService errorMessageService,
            IUrlService urlService)
        {
            _listDao = listDao;
            _contentService = contentService;
            _listItemTrackingServices = listItemTrackingServices;
            _issuerService = issuerService;
            _userContext = userContext;
            _authorizationService = authorizationService;
            _calendarService = calendarService;
            _errorMessageService = errorMessageService;
            _urlService = urlService;
        }

        [CustomAuthorize]
        public ActionResult Index(int id, string refreshAction = "")
        {
            var list = _listDao.GetById(id);
            if (!string.IsNullOrEmpty(refreshAction))
            {
                ViewBag.refreshAction = refreshAction;
            }

            SetPageTitle(list.Name + " List");

            if (!list.ListFieldDefinitions.FilterByPermission().Any())
            {
                ViewBag.Message = $"No Field Definitions found in the database for the List: {list.Name}";
                return View("UnderConstruction");
            }

            var listFieldDefinitions = list.ListFieldDefinitions.FilterByPermission().OrderBy(o => o.Order);
            var idColumn = listFieldDefinitions.FirstOrDefault(o => o.FieldDefinition.FieldType.IsIdentifierField());

            return View(GetListModel(id, list, listFieldDefinitions, idColumn));
        }

        private static ListModel GetListModel(int id, List list, IEnumerable<ListFieldDefinition> listFieldDefinitions, ListFieldDefinition idColumn)
        {
            var listModel = new ListModel
            {
                Title = list.Name,
                ShowTrackingFields = list.ListFieldDefinitions.FilterByPermission().HasTrackingFields(),
                Columns =
                    listFieldDefinitions
                        .ExcludeTrackingFields()
                        .Where(o => o.VisibleInList)
                        .Select(
                            o =>
                                new ColumnModel
                                {
                                    Description = o.FieldDefinition.Description,
                                    Name = o.FieldDefinition.Name,
                                    OrderDirection = o.DefaultOrder,
                                    Order = o.Order,
                                    FieldType = o.FieldDefinition.FieldTypeCode

                                }).OrderBy(c => c.Order).ThenBy(c => c.Name).ToList(),
                IdColumnName = idColumn != null ? idColumn.FieldDefinition.Name : null,
                Id = id,
                CanExpire = list.CanExpire
            };

            if (list.ListFieldDefinitions.FilterByPermission().HasTrackingFields())
            {
                listModel.CreatedDateFieldName =
                    list.ListFieldDefinitions.FilterByPermission().GetFieldNameByTypeCode(FieldType.TrackingCreatedDate);
                listModel.ModifiedDateFieldName =
                    list.ListFieldDefinitions.FilterByPermission().GetFieldNameByTypeCode(FieldType.TrackingUpdatedDate);

                if (string.IsNullOrEmpty(listModel.CreatedDateFieldName) ||
                    string.IsNullOrEmpty(listModel.ModifiedDateFieldName))
                {
                    LogManager.EventFactory.Create()
                        .Level(LoggingEventLevel.Alert)
                        .Text($"No CreatedDate or ModifiedDate tracking field defined for List: {list.Name} ({list.ListId})")
                        .Push();
                }
            }

            ReplaceTranslationsField(ref listModel, list);

            return listModel;
        }

        private static void ReplaceTranslationsField(ref ListModel listModel, List list)
        {
            var translationsField = list.ListFieldDefinitions.FirstOrDefault(d => d.FieldDefinition.FieldTypeCode == FieldType.Translations);
            if (translationsField != null)
            {
                if (!string.IsNullOrEmpty(translationsField.FieldDefinition.CustomSettings))
                {
                    var translationsSettings = translationsField.FieldDefinition.GetSettings<TranslationsSettings>();
                    if (translationsSettings != null && !string.IsNullOrEmpty(translationsSettings.ListViewFieldName))
                    {
                        foreach (var column in listModel.Columns)
                        {
                            if (column.Name == translationsField.FieldDefinition.Name)
                            {
                                column.Description = translationsSettings.ListViewFieldName;
                                break;
                            }
                        }
                    }
                }
            }
        }

        [CustomAuthorize]
        public ActionResult GetContent(GetListItemsDataTablesRequest request)
        {
            var list = _listDao.GetById(request.ListId);
            var result = _contentService.GetContentFor(list, UserContext.SelectedRegion?.Trim(), request.Start, request.Length, request.Search.Value, request.GetSortedColumns(), (list.CanExpire ? (bool?)request.isExpired : null));
            foreach (var row in result.Data)
            {
                var fields = row as IDictionary<string, object>;
                var keys = fields.Keys.ToList();
                foreach (var key in keys)
                {
                    if (!string.IsNullOrEmpty(key) && fields[key] != null && fields[key] is string)
                    {
                        fields[key] = list.ListFieldDefinitions.Any(ctf => ctf.FieldDefinition.Name.Equals(key, StringComparison.OrdinalIgnoreCase)
                                      && ctf.FieldDefinition.FieldTypeCode.Equals(FieldType.HtmlText, StringComparison.OrdinalIgnoreCase)) ?
                                      ((string)fields[key]).SanitizeHtmlString() :
                                      list.ListFieldDefinitions.Any(ctf => ctf.FieldDefinition.Name.Equals(key, StringComparison.OrdinalIgnoreCase)
                                      && ctf.FieldDefinition.FieldType.FieldTypeCode.Equals(FieldType.Image, StringComparison.OrdinalIgnoreCase) && ctf.VisibleInList == true) ?
                                      _urlService.GetStaticImageURL((string)fields[key], 64, 64, false, 95, false) :
                                      ((string)fields[key]).StripHtml();
                    }
                }
            }

            return JsonNet(new DataTablesResponse(request.Draw, result.Data, result.Total, result.Total));
        }

        public ActionResult GetTrackingInfo(string id, int listId)
        {
            if (!_authorizationService.Authorize(
                null,
                Convert.ToString(ControllerContext.RequestContext.RouteData.Values["controller"]),
                Convert.ToString(ControllerContext.RequestContext.RouteData.Values["action"]),
                listId.ToString()))
            {
                throw new AuthorizationException("Unauthorized");
            }

            var trackingInfo = _listItemTrackingServices.GetTrackingFieldsInfo(id, listId);

            return JsonNet(
                            new
                            {
                                trackingInfo.CreatedBy,
                                CreatedDate = trackingInfo.CreatedDate.ToString(CultureInfo.InvariantCulture),
                                trackingInfo.ModifiedBy,
                                ModifiedDate = trackingInfo.ModifiedDate.HasValue ? trackingInfo.ModifiedDate.ToString() : null
                            });
        }

        [CustomAuthorize]
        [HttpPost]
        [UnitOfWork]
        public ActionResult Delete(int listId, string itemId)
        {
            try
            {
                bool deleted = false;

site/Mastercard.MarketingCenter.Cms/Controllers/TagController.cs
using Mastercard.MarketingCenter.Cms.Core.ActionFilters;
using Mastercard.MarketingCenter.Cms.Models;
using Mastercard.MarketingCenter.Cms.Services.Core;
using Mastercard.MarketingCenter.Cms.Services.Services;
using Mastercard.MarketingCenter.Common.Extensions;
using Mastercard.MarketingCenter.Common.Services;
using Mastercard.MarketingCenter.Data;
using Mastercard.MarketingCenter.Data.Daos;
using Slam.Cms.Data;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Mastercard.MarketingCenter.Cms.Controllers
{
    [CustomAuthorize]
    public class TagController : CmsBaseController
    {
        private readonly TagCategoryDao _tagCategoryDao;
        private readonly RegionDao _regionDao;
        private readonly SlamContext _slamContext;
        private readonly TagServices _tagServices;
        private readonly IdGeneratorService _idGeneratorService;
        private readonly ListDao _listDao;
        private readonly ContentService _contentService;
        private readonly ISqlCacheRepository _sqlCacheRepository;

        public TagController(TagCategoryDao tagCategoryDao, RegionDao regionDao, SlamContext slamContext, TagServices tagServices, IdGeneratorService idGeneratorService, ListDao listDao, ContentService contentService, ISqlCacheRepository sqlCacheRepository)
        {
            _tagCategoryDao = tagCategoryDao;
            _regionDao = regionDao;
            _slamContext = slamContext;
            _tagServices = tagServices;
            _idGeneratorService = idGeneratorService;
            _listDao = listDao;
            _contentService = contentService;
            _sqlCacheRepository = sqlCacheRepository;
        }

        public ActionResult CreateCategory()
        {
            SetPageTitle("Create Tag Category");

            var tagCategoryModel = new TagCategoryModel { TagBrowser = "Yes" };
            return View(tagCategoryModel);
        }

        public ActionResult Create(string id)
        {
            SetPageTitle("Create Tag");

            var tagList = _listDao.GetById(MarketingCenterDbConstants.ListIds.TagListId);

            var model = new ListItemModel
            {
                ListId = MarketingCenterDbConstants.ListIds.TagListId,
                ListFieldDefinitions = tagList.ListFieldDefinitions.ExcludeTrackingFields().Where(o => !o.HiddenInNew),
                ListTitle = tagList.Name
            };

            ViewBag.ParentId = id;

            return View(model);
        }

        [HttpPost]
        [UnitOfWork]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ListItemModel model)
        {
            ValidateModel(model);

            var parentIdValue = Request.Form["ParentId"];

            if (ModelState.IsValid)
            {
                var tagId = _contentService.AddItemContent(model.ListId, model.ListItemData, UserContext.User.UserId);

                _tagServices.AddNewTagToHierarchy(tagId, parentIdValue);

                return RedirectToAction("TagManager", new { invalidateTagTree = "true" });
            }

            ViewBag.ParentId = parentIdValue;

            return View("Create", model);
        }

        [HttpPost]
        [UnitOfWork]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCategory(TagCategoryModel tagCategoryModel)
        {
            if (ModelState.IsValid)
            {
                var newTagCategory = new Data.Entities.TagCategory
                {
                    DisplayOrder = tagCategoryModel.DisplayOrder,
                    Featurable = tagCategoryModel.Featurable,
                    IsRelatable = tagCategoryModel.IsRelatable,
                    TagBrowser = tagCategoryModel.TagBrowser,
                    Title = tagCategoryModel.Title,
                    TagCategoryId = _idGeneratorService.GetNewUniqueId()
                };
                tagCategoryModel.GetType().GetProperties().ToList().ForEach(
                p => { if (p.GetType().Name.Equals("String", StringComparison.CurrentCulture)) p.GetValue(tagCategoryModel, null)?.ToString().DecodeHtml(); }

                );
                _tagCategoryDao.Add(newTagCategory);

                return RedirectToAction("TagManager", new { invalidateTagTree = "true" });
            }

            return View(tagCategoryModel);
        }

        [HttpPost]
        [UnitOfWork]
        public ActionResult DeleteTagCategory(string id)
        {
            _tagServices.DeleteTagCategory(id);

            return JsonNet(new { ok = true });
        }

        [HttpPost]
        [UnitOfWork]
        public ActionResult DeleteTag(string id)
        {
            _tagServices.DeleteTag(id);

            return JsonNet(new { ok = true });
        }

        [HttpPost]
        [UnitOfWork]
        public ActionResult RemoveFromHierarchy(string id)
        {
            if (id.StartsWith("p"))
            {
                var positionId = Convert.ToInt32(id.Replace("p", string.Empty));
                _tagServices.DeleteTagHierarchyPosition(positionId);

                return JsonNet(new { ok = true });
            }

            return JsonNet(new { ok = false });
        }

        public ActionResult TagManager(string invalidateTagTree = "false")
        {
            SetPageTitle("Tag Manager");

            if (invalidateTagTree == "true")
            {
                _slamContext.InvalidateAllTags();
                _regionDao.GetAll().ForEach(r => _sqlCacheRepository.SaveRegionInvalidator($"RegionTag_{r.IdTrimmed}"));
            }

            var tagTree = _slamContext.GetTagTree();

            return View(tagTree.Root);
        }

        public ActionResult UpdateCategory(string id)
        {
            var tagCategory = _tagCategoryDao.GetById(id);

            SetPageTitle("Update Tag Category");

            var model = new TagCategoryModel
            {
                DisplayOrder = tagCategory.DisplayOrder,
                Featurable = tagCategory.Featurable,
                Title = tagCategory.Title,
                IsRelatable = tagCategory.IsRelatable,
                TagBrowser = tagCategory.TagBrowser,
                TagCategoryId = tagCategory.TagCategoryId
            };

            return View(model);
        }

        [HttpPost]
        [UnitOfWork]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateCategory(TagCategoryModel tagCategoryModel)
        {
            if (ModelState.IsValid)
            {
                var tagCategory = _tagCategoryDao.GetById(tagCategoryModel.TagCategoryId);

                tagCategory.DisplayOrder = tagCategoryModel.DisplayOrder;
                tagCategory.Featurable = tagCategoryModel.Featurable;
                tagCategory.Title = tagCategoryModel.Title;
                tagCategory.TagBrowser = tagCategoryModel.TagBrowser;
                tagCategory.IsRelatable = tagCategoryModel.IsRelatable;

                return RedirectToAction("TagManager", new { invalidateTagTree = "true" });
            }

            return View(tagCategoryModel);
        }

        private void ValidateModel(ListItemModel model)
        {
            var list = _listDao.GetById(MarketingCenterDbConstants.ListIds.TagListId);
            var fields = list.ListFieldDefinitions.Select(o => o.FieldDefinition);

            var validationErros = _contentService.ValidateData(fields, model.ListItemData);

            validationErros.ForEach(err => ModelState.AddModelError(err.Key, err.ErrorMessage));
        }
    }
}

site/Mastercard.MarketingCenter.Cms/Views/Tag/Create.cshtml
@model ListItemModel

@section head
{
    @System.Web.Optimization.Scripts.Render("~/bundles/content")
    @System.Web.Optimization.Styles.Render("~/Content/content")

    <script>
        $(document).ready(function () {
            var contentItemCrud = new ContentItemCrud();
            contentItemCrud.initialize();

            @Html.RenderClientEvents()
        });

    </script>
}


@section HeaderTitle
{
    New Tag
}

<div class="ibox-content">

    @Html.Partial("_ErrorAlert")

    @using (Html.BeginForm("Create", "Tag", FormMethod.Post, new { @class = "form-horizontal" }))
    {@Html.AntiForgeryToken()
        @Html.HiddenFor(o => o.ListId)
        
        <input type="hidden" name="ParentId" value="@ViewBag.ParentId"/>

        @Html.EditorForModel()

        <hr />
        <div class="form-group">
            <div class="col-md-6 col-md-offset-3">
                <div class="pull-right">
                    <a href="@(string.IsNullOrEmpty(Model.ReturnUrl) ? Url.Action("Index", "List", new { id = Model.ListId }) :  HttpUtility.UrlEncode( HttpUtility.UrlDecode(Model.ReturnUrl??String.Empty)))" class="btn btn-white"><span class="fa fa-remove"></span>&nbsp;&nbsp;Cancel</a>
                </div>
                <button class="btn btn-primary" type="submit"><span class="fa fa-plus"></span>&nbsp;&nbsp;Create</button>
            </div>
        </div>
    }
</div>

site/Mastercard.MarketingCenter.Cms/Views/Tag/CreateCategory.cshtml
@model TagCategoryModel

@section HeaderTitle
{
    Create new Tag Category
}

<div class="ibox-content">

    @using (Html.BeginForm("CreateCategory", "Tag", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.Partial("_TagCategoryFieldPartial", Model)

        <hr />
        <div class="form-group">
            <div class="col-md-6 col-md-offset-3">
                @Html.ActionLink("Cancel", "TagManager", "Tag", null, new { @class = "btn btn-white" })
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </div>

    }

</div>

site/Mastercard.MarketingCenter.Cms/Views/Tag/TagManager.cshtml
@model Slam.Cms.Data.TagTreeNode
@section HeaderTitle
{
    <h2><em class="fa fa-bar-chart"></em>&nbsp;Tag Manager</h2>
}
<div class="ibox-content">
    @Html.GlyphButton("Add New Tag Category", "CreateCategory", "Tag", new { @class = "btn btn-primary" }, new { @class = "fa fa-plus" })
    <hr />
    <div style="width: 600px" id="tagManager">
        @Html.BuildTagManager(Model)
    </div>
</div>
<div id="tagActions" class="dropdown" style="position: absolute;">
    <ul class="dropdown-menu" id="tagMenu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="add-tag" id="newTag">Add new Tag</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#" id="editTag">Edit Tag</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#" id="remove">Remove From Hierarchy</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#" id="deleteTag">Delete Tag</a></li>
    </ul>
</div>
<div class="dropdown" id="categoryActions" style="position: absolute;">
    <ul class="dropdown-menu" id="categoryMenu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#" id="editTagCategory">Edit Tag Category</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="add-tag" id="newTagCat">Add New Tag</a></li>
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#" id="deleteTagCategory">Delete Category</a></li>
    </ul>
</div>
<input type="hidden" id="parentId" name="parentId" />
<input type="hidden" id="tagId" name="tagId" />
<input type="hidden" id="catId" name="catId" />
<script>
    $(document).ready(function () {

        var invalidateRedirect = '@Url.Action("TagManager", new { invalidateTagTree = "true" })';

        var captureMouse = true;
        var mouseX;
        var mouseY;

        mousemoveHandler = function (e) {
            mouseX = e.pageX;
            mouseY = e.pageY;
        };

        $(document).mousemove(mousemoveHandler);

        $("#tagManager").mouseover(function () {
            if (captureMouse) {
                $('#tagActions').css({ 'top': mouseY - 180, 'left': mouseX - 190 }).fadeIn('slow');
                $('#categoryActions').css({ 'top': mouseY - 180, 'left': mouseX - 190 }).fadeIn('slow');
            }
        });

        $("span[class=name]").mousedown(function (e) {
            if (e.button == 2) {
                $("#tagMenu").hide();
                $("#categoryMenu").hide();

                $(document).one('contextmenu', function (e) { // Not compatible with IE < 9
                    e.preventDefault();
                    return false;
                }, false);
                $(document).off('mousemove');

                captureMouse = false;
                $("#parentId").val($(this).data("parentid"));
                $("#tagId").val($(this).data("id"));
                $("#catId").val($(this).data("catid"));

                if ($(this).data('catid')) {
                    $("#categoryMenu").show();
                }
                else {
                    $("#tagMenu").show();
                }
                return false;
            }
            return true;
        });

        $("span[class=name]").mouseup(function (e) {
            if (e.button == 2) {
                captureMouse = false;
                return false;
            }
            return true;
        });

        $(document).click(function (e) {
            if (e.button != 2) {
                $("#tagMenu").hide();
                $("#categoryMenu").hide();
                $(document).off('contextmenu');
                $(document).mousemove(mousemoveHandler);
            }
            captureMouse = true;
            return true;
        });

        $(".add-tag").click(function (e) {
            var id = $("#parentId").val();
            window.location = '@Url.Action("Create", "Tag")' + '?id=' + id;
        });

        $("#editTag").click(function (e) {
            var id = $("#tagId").val();
            window.location = '@Html.Raw(Url.Action("Edit", "List", new { listId = Mastercard.MarketingCenter.Data.MarketingCenterDbConstants.ListIds.TagListId, returnUrl = Url.Action("TagManager", new { invalidateTagTree = "true" }) }))' + '&id=' + id;
        });

        $("#editTagCategory").click(function (e) {
            var id = $("#catId").val();
            window.location = '@Url.Action("UpdateCategory", "Tag")/' + id;
        });

        $("#deleteTag").click(function (e) {
            var id = $("#tagId").val();
            $.post('@Url.Action("DeleteTag", "Tag")', { id: id }).done(function (data) {
                if (data.responseCode == 200) { window.location = invalidateRedirect; }
            }, "json").fail(function () { alert("The Tag cannot be removed because there is current content / issuers related to that Tag."); });
        });

        $("#remove").click(function (e) {
            var id = $("#parentId").val();

            $.post('@Url.Action("RemoveFromHierarchy", "Tag")', { id: id }, function (data) {
                window.location = invalidateRedirect;
            }, "json");
        });

        $("#deleteTagCategory").click(function (e) {
            var id = $("#catId").val();

            $.post('@Url.Action("DeleteTagCategory", "Tag")', { id: id }, function (data) {
                window.location = invalidateRedirect;

            }, "json");
        });
    });
</script>

site/Mastercard.MarketingCenter.Cms/Views/Tag/UpdateCategory.cshtml
@model TagCategoryModel

@section HeaderTitle
{
    Edit Tag Category
}

<div class="ibox-content">

    @using (Html.BeginForm("UpdateCategory", "Tag", FormMethod.Post, new { @class = "form-horizontal" }))
    {   @Html.AntiForgeryToken()
        @Html.Partial("_TagCategoryFieldPartial", Model)

        <hr />

        <div class="form-group">
            <div class="col-md-6 col-sm-offset-3">
                @Html.ActionLink("Cancel", "TagManager", "Tag", null, new { @class = "btn btn-white" })
                <button class="btn btn-primary" type="submit">Update</button>
            </div>
        </div>

    }

</div>

site/Mastercard.MarketingCenter.Cms/Views/Tag/_TagCategoryFieldPartial.cshtml
@model TagCategoryModel
@Html.HiddenFor(o => o.TagCategoryId)

@Html.Partial("_ErrorAlert")
@using (Html.BeginFormGroup(o => o.Title))
{
    <div class="form-group">
        <label class="col-md-3 control-label">Title <span class="req-mark">*</span></label>
        <div class="col-md-6">@Html.TextBoxFor(o => o.Title, new { @class = "form-control" })</div>
    </div>
}
@using (Html.BeginFormGroup(o => o.TagBrowser))
{
    <div class="form-group">
        <div>
            <label class="col-md-3 control-label">Tag Browser</label>
        </div>
        <div class="col-md-6">
            <div class="radio"><label>@Html.RadioButtonFor(o => o.TagBrowser, "Yes")Yes</label></div>
            <div class="radio"><label>@Html.RadioButtonFor(o => o.TagBrowser, "No")No</label></div>
            <div class="radio"><label>@Html.RadioButtonFor(o => o.TagBrowser, "Filtered")Filtered</label></div>
        </div>
    </div>
}
@using (Html.BeginFormGroup(o => o.DisplayOrder))
{
    <div class="form-group">
        <label class="col-md-3 control-label">Display Order <span class="req-mark">*</span></label>
        <div class="col-md-6">@Html.TextBoxFor(o => o.DisplayOrder, new { @class = "form-control", @maxlength = "4" })</div>
    </div>
}
@using (Html.BeginFormGroup(o => o.Featurable))
{
    <div class="form-group">
        <label class="col-md-3 control-label">Featurable</label>
        <div class="col-md-6">
            @Html.DropDownListFor(o => o.Featurable, new List<SelectListItem> { new SelectListItem { Text = "Conditional", Value = "Conditional" },
                                  new SelectListItem { Text = "Always", Value = "Always" }, new SelectListItem { Text = "Never", Value = "Never" } }, new { @class = "form-control m-b" })
        </div>
    </div>
}
@using (Html.BeginFormGroup(o => o.IsRelatable))
{
    <div class="form-group">
        <label class="col-md-3 control-label">Relatable</label>
        <div class="col-md-6">
            <div class="onoffswitch">
                @Html.CheckBoxFor(o => o.IsRelatable)
                <label class="onoffswitch-label" for="IsRelatable"></label>
            </div>
        </div>
    </div>
}