site/Mastercard.MarketingCenter.Cms/Models/Content/ContentCommentViewModel.cs
namespace Mastercard.MarketingCenter.Cms.Models
{
    public class ContentCommentViewModel
    {
        public string SenderUserAvatar { get; set; }
        public string ContentItemId { get; set; }
        public string BackLink { get; set; } = "";
        public bool IsNew { get; set; }
        public int CommentsTotal { get; set; }
        /// <summary>
        /// If <value>true</value> then BO is notified about added comments, otherwise: admin
        /// </summary>
        public bool IsAdmin { get; set; }
    }
}

site/Mastercard.MarketingCenter.Cms/Controllers/ContentCommentController.cs
using Mastercard.MarketingCenter.Cms.Core.ActionFilters;
using Mastercard.MarketingCenter.Cms.Models;
using Mastercard.MarketingCenter.Cms.Services.Services;
using Mastercard.MarketingCenter.Common.Extensions;
using Mastercard.MarketingCenter.Common.Interfaces;
using Mastercard.MarketingCenter.Data;
using Mastercard.MarketingCenter.Data.Entities;
using Mastercard.MarketingCenter.Services;
using Mastercard.MarketingCenter.Services.Interfaces;
using Newtonsoft.Json;
using Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using FilterStatus = Slam.Cms.Data.FilterStatus;

namespace Mastercard.MarketingCenter.Cms.Controllers
{
    public class ContentCommentController : Controller
    {
        private readonly IUserService _userService;
        private readonly IContentCommentServices _contentCommentServices;
        private readonly IContentItemService _contentItemService;
        private readonly IEmailService _emailServices;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IBussinesOwnerService _bussinesOwnerService;
        private readonly UserContext _userContext;
        private readonly ContentService _contentService;
        private readonly IStandardResponseService _standardResponseService;

        public ContentCommentController(
            IContentCommentServices contentCommentServices,
            IContentItemService contentItemService,
            IEmailService emailServices,
            IUserService userService,
            IUnitOfWork unitOfWork,
            IBussinesOwnerService bussinesOwnerServices,
            UserContext userContext,
            ContentService contentService,
            IStandardResponseService standardResponseService)
        {
            _bussinesOwnerService = bussinesOwnerServices;
            _contentCommentServices = contentCommentServices;
            _emailServices = emailServices;
            _userService = userService;
            _contentItemService = contentItemService;
            _unitOfWork = unitOfWork;
            _userContext = userContext;
            _contentService = contentService;
            _standardResponseService = standardResponseService;
        }

        public ActionResult Widget(
            string contentItemID,
            string backLink = "",
            List<string> commentsSeed = null,
            bool isNew = false,
            bool isAdmin = false)
        {
            var usersAvatar = new string(_userContext.User.FullName.Split(' ').Select(n => n.FirstOrDefault()).ToArray());
            ViewData["commentsSeed"] = commentsSeed == null || commentsSeed.Count() == 0 ? null : JsonConvert.SerializeObject(commentsSeed);
            return PartialView(new ContentCommentViewModel
            {
                ContentItemId = contentItemID,
                BackLink = backLink,
                IsNew = isNew,
                SenderUserAvatar = usersAvatar,
                CommentsTotal = _contentCommentServices.GetCommentsByContent(contentItemID),
                IsAdmin = isAdmin
            });
        }

        [BusinessOwnerExpirationManagementEnabled]
        [HttpPost]
        public ActionResult AddNew(string contentItemID, string commentBody, bool isAdmin)
        {
            if (string.IsNullOrEmpty(contentItemID) || string.IsNullOrEmpty(commentBody))
            {
                return new HttpNotFoundResult();
            }

            User businessOwner = null;
            if (isAdmin)
            {
                // get business owner email
                var contentItemData = _contentService.GetContentItemData(contentItemID);
                var businessOwnerId = _bussinesOwnerService.GetBusinessOwnerId(contentItemData);
                businessOwner = businessOwnerId > 0 ? _userService.GetUser(businessOwnerId) : null;

                if (businessOwner == null)
                {
                    Response.StatusCode = 400;
                    return _standardResponseService.GetErrorResponse("NoBusinessOwner", ContentItemComments.NoBusinessOwnerErrorMessage);
                }
            }

            var senderUser = _userContext.User;
            var contentItem = _contentItemService.GetAssetContentItem(contentItemID, FilterStatus.None);
            var isInsertSuccessful = _contentCommentServices.AddNew(senderUser.UserId, contentItem.ContentTypeId, contentItem.ContentItemId, commentBody);
            if (isInsertSuccessful)
            {
                if (isAdmin)
                {
                    _bussinesOwnerService.SendContentCommentNotificationToBussinessOwner(
                        ((IContentItemWithTitle)contentItem).Title,
                        contentItem.ContentItemId,
                        commentBody,
                        contentItem.RegionId,
                        senderUser.FullName,
                        businessOwner.Email,
                        null);
                }
                else
                {
                    _bussinesOwnerService.SendContentCommentNotificationToAdmin(
                        ((IContentItemWithTitle)contentItem).Title,
                        contentItem.ContentItemId,
                        commentBody,
                        contentItem.RegionId,
                        senderUser.FullName,
                        null);
                }

                _unitOfWork.Commit();

                return new HttpStatusCodeResult(HttpStatusCode.NoContent);
            }
            else
            {
                return new HttpNotFoundResult();
            }
        }

        [HttpPost]
        public JsonResult GetPaged(string contentItemID, int pageNumber, int pageSize = 5)
        {
            var contentItem = _contentItemService.GetContentItem(contentItemID);
            return Json(_contentCommentServices.GetPaged(contentItem.ContentTypeId, contentItem.ContentItemId, pageNumber, pageSize));
        }

        [BusinessOwnerExpirationManagementEnabled]
        [HttpPost]
        public ActionResult BulkExtend(string[] contentItemIDs, bool shouldExtend, string userFullName)
        {
            return PartialView(new BulkExpirationExtensionViewModel
            {
                ContentItemIDs = contentItemIDs,
                ShouldExtend = shouldExtend,
                UserFullName = userFullName
            });
        }

        [BusinessOwnerExpirationManagementEnabled]
        [HttpGet]
        public ActionResult Extend(string contentItemID, DateTime expirationDate, string contentTitle, string userFullName, bool shouldExtend)
        {
            return PartialView(new ExpirationExtensionViewModel
            {
                ContentItemID = contentItemID.GetAsLiveContentItemId(),
                ExpirationDate = expirationDate,
                Title = contentTitle,
                UserFullName = userFullName,
                ShouldExtend = shouldExtend
            });
        }

        [BusinessOwnerExpirationManagementEnabled]
        [HttpPost]
        public ActionResult BulkExtensionComment(string extendMessage, string[] contentItemIDs, bool shouldExtend, int daysToExtend = 0)
        {
            if (contentItemIDs == null || contentItemIDs.Length == 0)
            {
                return HttpNotFound();
            }

            var senderUser = _userContext.User;
            IEnumerable<Slam.Cms.Data.ContentItem> slamContentItems;
            var isInsertSuccessful = _bussinesOwnerService.ExtendOrNotExtend(contentItemIDs, senderUser.UserId, shouldExtend, extendMessage, daysToExtend, out slamContentItems);
            if (!isInsertSuccessful)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Conflict);
            }

            _emailServices.SendBulkExtensionNotification(slamContentItems, shouldExtend, extendMessage, daysToExtend, senderUser.FullName);
            _unitOfWork.Commit();

            return new HttpStatusCodeResult(HttpStatusCode.NoContent);
        }

        [BusinessOwnerExpirationManagementEnabled]
        [HttpPost]
        public ActionResult ExtensionComment(string extendMessage, string contentItemID, bool shouldExtend, int daysToExtend = 0)
        {
            if (string.IsNullOrEmpty(contentItemID) || string.IsNullOrEmpty(extendMessage))
            {
                return HttpNotFound();
            }

            var senderUser = _userContext.User;
            IEnumerable<Slam.Cms.Data.ContentItem> slamContentItems;
            var isInsertSuccessful = _bussinesOwnerService.ExtendOrNotExtend(new List<string> { contentItemID }, senderUser.UserId, shouldExtend, extendMessage, daysToExtend, out slamContentItems);
            if (isInsertSuccessful)
            {
                _emailServices.SendExtensionNotification(
                    slamContentItems.Select(x => (IContentItemWithTitle)x).FirstOrDefault()?.Title,
                    contentItemID, shouldExtend, extendMessage, daysToExtend,
                    _contentItemService.GetContentItem(contentItemID)?.RegionId,
                    senderUser.FullName);

                _unitOfWork.Commit();
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.Conflict);
            }

            return new HttpStatusCodeResult(HttpStatusCode.NoContent);
        }
    }
}

site/Mastercard.MarketingCenter.Cms/Views/ContentComment/BulkExtend.cshtml
@model BulkExpirationExtensionViewModel
@{
    Layout = null;
}

@*Begin of Modal that Exposes Extend Do Not Extend Functionality*@
<div class="mc-modal" id="modalExtend">
    @Html.Partial("~/Views/Shared/_ModalSuccessError.cshtml")
    <div class="mc-modal--content main--modal">
        <div class="mc-modal--header">
            <a class="close-link" href="javascript:void(0);"><img width="32" alt="" src="/admin/Content/css/ContentComments/images/pop-up_close_icon.png"></a>
            <h5>@Resources.ExpirationModals.TitlePrefix</h5>
            <h2>@(Model.ShouldExtend ? Resources.ExpirationModals.BulkExtendDescription : Resources.ExpirationModals.DoNotExtendDescription)</h2>
            <p>@(Model.ShouldExtend ? Resources.ExpirationModals.BulkExtendAction : Resources.ExpirationModals.DoNotExtendAction)</p>
        </div>
        <div class="mc-modal--body">
            <div class="mc-form-group">
                <label for="">@Resources.ExpirationModals.BussinesOwnlerLabel</label>
                <div class="mc-field">@Model.UserFullName</div>
            </div>
            @if (Model.ShouldExtend)
            {
                <div class="mc-form-group">
                    <div class="dateDropDown">
                        <label for="">@Resources.ExpirationModals.ExtendExpirationDropDown</label>
                        @Html.DropDownList("dateChooser", new SelectListItem[] {
                            new SelectListItem { Text = "30 "+ Resources.BusinessOwnerPages.Days, Value = "30" },
                            new SelectListItem { Text = "60 "+ Resources.BusinessOwnerPages.Days, Value = "60" },
                            new SelectListItem { Text = "90 "+ Resources.BusinessOwnerPages.Days, Value = "90" },
                            new SelectListItem { Text = "120 "+ Resources.BusinessOwnerPages.Days, Value = "120" },
                            new SelectListItem { Text = "180 "+ Resources.BusinessOwnerPages.Days, Value = "180" },
                        })
                    </div>
                </div><br />
            }
            <div class="mc-form-group input">
                <label class="messageLabel" for="">@Resources.ExpirationModals.MessageLabel</label>
                <div class="mc-field">
                    <input name="message" type="text" value="@(Model.ShouldExtend?Resources.ExpirationModals.BulkExtendExample: Resources.ExpirationModals.BulkDoNotExtendExample)">
                </div>
            </div>

            <div class="mc-buttons">
                <a class="mc-btn close-link" href="javascript:void(0);">@Resources.BusinessOwnerPages.Cancel</a>
                <a class="mc-btn primary" id="ConfirmButton" href="javascript:void(0);">@Resources.ExpirationModals.ConfirmButtonCaption</a>
            </div>
        </div>
    </div>
</div>

@*End of Modals that Exposes Extend Do Not Extend Functionality*@
<script src="~/Content/js/ContentComments/Modals.js"></script>
<script>
    bulkExpirationCommentModals('#modalExtend [name=message]', '#modalExtend #ConfirmButton',
        "@Url.Action("BulkExtensionComment", "contentComment")", @Html.Raw(Json.Encode(Model.ContentItemIDs)),
        "@Model.ShouldExtend", '#modalExtend .messageLabel',"@Resources.ContentItemComments.WriteAMessageError");
</script>

site/Mastercard.MarketingCenter.Cms/Views/ContentComment/Extend.cshtml
@model ExpirationExtensionViewModel
@{
    Layout = null;
}

@*Begin of Modal that Exposes Extend Do Not Extend Functionality*@
<div class="mc-modal" id="modalExtend">
    @Html.Partial("~/Views/Shared/_ModalSuccessError.cshtml")
    <div class="mc-modal--content main--modal">
        <div class="mc-modal--header">
            <a class="close-link" href="javascript:void(0);"><img width="32" alt="" src="/admin/Content/css/ContentComments/images/pop-up_close_icon.png"></a>
            <h5>@Resources.ExpirationModals.TitlePrefix</h5>
            <h2>@(Model.ShouldExtend ? Resources.ExpirationModals.ExtendDescription : Resources.ExpirationModals.DoNotExtendDescription)</h2>
            <p>@(Model.ShouldExtend ? Resources.ExpirationModals.ExtendAction : Resources.ExpirationModals.DoNotExtendAction)</p>
        </div>
        <div class="mc-modal--body">
            <div class="mc-form-group">
                <label for="">@Resources.ExpirationModals.BussinesOwnlerLabel</label>
                <div class="mc-field">@Model.UserFullName</div>
            </div>
            <div class="mc-form-group">
                <label for="">@Resources.ExpirationModals.AssetTitleLAbel</label>
                <div class="mc-field">@Html.Raw(Model.Title)</div>
            </div>
            @if (Model.ShouldExtend) { 
            <div class="mc-form-group">
                <div class="dateDropDown">
                    <label for="">@Resources.ExpirationModals.ExtendExpirationDropDown</label>
                    @Html.DropDownList("dateChooser", new SelectListItem[] {
                        new SelectListItem { Text = "30 "+ Resources.BusinessOwnerPages.Days, Value = "30" },
                        new SelectListItem { Text = "60 "+ Resources.BusinessOwnerPages.Days, Value = "60" },
                        new SelectListItem { Text = "90 "+ Resources.BusinessOwnerPages.Days, Value = "90" },
                        new SelectListItem { Text = "120 "+ Resources.BusinessOwnerPages.Days, Value = "120" },
                        new SelectListItem { Text = "180 "+ Resources.BusinessOwnerPages.Days, Value = "180" },
                    })
                </div>
            </div><br />
            }
            else {
            <div class="mc-form-group">
                <label for="">@Resources.ExpirationModals.ExtendExpiresOn</label>
                <div class="mc-field">@Html.Raw(Model.ExpirationDate.ToString("d"))</div>
            </div>
            }
            <div class="mc-form-group input">
                <label class="messageLabel" for="">@Resources.ExpirationModals.MessageLabel</label>
                <div class="mc-field">
                    <input name="message" type="text" value="@(Model.ShouldExtend ? Resources.ExpirationModals.ExtendExample : Resources.ExpirationModals.DoNotExtendExample)">
                </div>
            </div>
            <div class="mc-buttons">
                <a class="mc-btn close-link" href="javascript:void(0);">@Resources.BusinessOwnerPages.Cancel</a>
                <a class="mc-btn primary" id="ConfirmButton" href="javascript:void(0);">@Resources.ExpirationModals.ConfirmButtonCaption</a>
            </div>
        </div>
    </div>
</div>

@*End of Modals that Exposes Extend Do Not Extend Functionality*@
<script src="~/Content/js/ContentComments/Modals.js"></script>
<script>
    expirationCommentModals('#modalExtend [name=message]', '#modalExtend #ConfirmButton', "@Url.Action("ExtensionComment", "ContentComment")",
        "@Model.ContentItemID", "@Model.ShouldExtend", "@Resources.ContentItemComments.WriteAMessageError", '#modalExtend .messageLabel');
</script>

site/Mastercard.MarketingCenter.Cms/Views/ContentComment/Widget.cshtml
@model ContentCommentViewModel
@{
    Layout = null;
    var commentsSeed = ViewData["commentsSeed"];
}
<div id="commentsWidget">
    @Html.Partial("~/Views/Shared/_ModalSuccessError.cshtml")
    @*Main comments modal Start*@
    <div id="modalComments" class="mc-comments mc-panel">
        <div class="mc-modal--header small-padd-bottom titles">
            <a href="javascript:void(0);" class="close-link"><img src="@Url.Content("~/Content/css/ContentComments/images/pop-up_close_icon.png")" width="32" alt=""></a>
            <span class="title"> @Resources.ContentItemComments.CommentsTitle</span>
            <span class="mc-comments-total" v-if="totalCommentsCount>0">@string.Format(Resources.ContentItemComments.TotalComments, "{{totalCommentsCount}}")</span>
        </div>
        <div class="mc-modal--body no-padd">
            <div id="mc-comments--body--wrapper" class="mc-comments--body--wrapper" v-cloak>
                <div class="mc-comments">

                    <div class="mc-comments--body" v-bind:class="{ empty: !comments.length }">
                        <div class="mc-comments--item"
                             v-if="comments.length"
                             v-for="(comment,index) in comments"
                             v-bind:class="{ me: comment.author=='ME' }"
                             v-bind:key="index">
                            <div class="mc-comments--author">
                                <div class="mc-comments--avatar">{{comment.avatar}}</div>
                            </div>
                            <div class="mc-comments--text">
                                <div class="mc-comments-added-date">{{comment.added}}</div>
                                <div>
                                    {{comment.text}}
                                </div>
                                <div class="line-wrapper">
                                    <div class="line left"></div>
                                </div>
                            </div>
                            <br />
                        </div>
                        <div v-if="!comments.length">
                            <p><img src="/admin/Content/css/ContentComments/images/empty_state_comments_icon.png" width="128" alt=""></p>
                            <p>@Resources.ContentItemComments.EmptyCommentsMessage</p>
                        </div>
                    </div>
                    <div class="mc-comments--form">
                        <div class="mc-comments--author">
                            <div class="mc-comments--avatar">@Model.SenderUserAvatar</div>
                        </div>
                        <input @@focus="inputFocus" class="mc-comments--input" type="text" id="newComment" name="newComment" placeholder="@Resources.ContentItemComments.CommentPlaceholder" v-model="newComment" v-on:keyup.enter="addComment">
                        <a href="javascript:void(0);" class="add-link" disabled="true" v-bind:disabled="newComment.length === 0 ? true : false" v-on:click="addComment">@Resources.ContentItemComments.Add</a>
                    </div>
                    <p style="color:#ff0000;" v-if="error" class="req-mark error">{{ error }}</p>
                </div>
                @*Main comments modal End*@
            </div>
        </div>
    </div>
    <script src="~/Content/js/ContentComments/Modals.js"></script>
    <script>
        var contentCommentModalsObj;
        //this function comes from \Content\js\ContentComments\Modals.js where most of the js scoped for this is included
        $(function () {
            contentCommentModalsObj = contentCommentModals(
                "@Url.Action("GetPaged")",
                "@Url.Action("AddNew")",
                "@Model.ContentItemId",
                "",
                "@Resources.ContentItemComments.Years",
                "@Resources.ContentItemComments.Months",
                "@Resources.ContentItemComments.Days",
                "@Resources.ContentItemComments.Hours",
                "@Resources.ContentItemComments.Minutes",
                "@Model.SenderUserAvatar",
                "@Resources.ContentItemComments.WriteAMessageError",
                null,
                JSON.parse(@Html.Raw(commentsSeed??"null")),
                @Json.Encode(Model.IsNew),
                @Model.CommentsTotal,
                @Json.Encode(Model.IsAdmin));
            $('.mc-comments--body').slimScroll({
                color: '#333',
                alwaysVisible: true,
                railVisible: true,
                railColor: '#222',
                allowPageScroll: true
            });

            $(".mc-modal#modalCommentsParent").click(function () {
                $("#modalCommentsParent .mc-modal--body").html("");
                $(this).closest(".mc-modal").removeClass("in");
            });
            $(".mc-modal #modalComments").click(function (e) {
                e.stopPropagation();
            });
            if ($("#modalComments .close-link").closest(".mc-modal").length == 0) {
                $("#modalComments .close-link").remove();
            }
        });
    </script>
</div>