site/Mastercard.MarketingCenter.Web/Controllers/ContentDetailController.cs
using Mastercard.MarketingCenter.Common.Extensions;
using Mastercard.MarketingCenter.Data;
using Mastercard.MarketingCenter.Data.DTOs;
using Mastercard.MarketingCenter.Data.Entities;
using Mastercard.MarketingCenter.Services;
using Mastercard.MarketingCenter.Services.Entities;
using Mastercard.MarketingCenter.Services.Exceptions;
using Mastercard.MarketingCenter.Services.Interfaces;
using Mastercard.MarketingCenter.Web.Core;
using Mastercard.MarketingCenter.Web.Core.Extensions;
using Mastercard.MarketingCenter.Web.Core.Models;
using Mastercard.MarketingCenter.Web.Core.Models.ContentItems;
using Mastercard.MarketingCenter.Web.Core.Services;
using Slam.Cms;
using Slam.Cms.Common;
using Slam.Cms.Configuration;
using Slam.Cms.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Status = Slam.Cms.Data.Status;

namespace Mastercard.MarketingCenter.Web.Controllers
{
    [Core.Filters.CustomAuthorize]
    public class ContentDetailController : BaseController
    {
        public const string CommandPrintOnDemand = "printondemmand";
        public const string CommandElectronicDelivery = "electronicdelivery";
        public const string CommandBatchPrint = "batchprint";
        private static readonly string OrderableAssetValidationMessage = System.Configuration.ConfigurationManager.AppSettings["ValidationMessages.OrderableAsset.Approver"];
        private readonly SlamContext _slamContext;
        private readonly SlamContextService _slamContextService;
        private readonly AssetRepository _assetRepository;
        private readonly IRegionService _regionService;
        private readonly MigratedContentRepository _migratedContentRepository;
        private readonly IContentItemService _contentItemService;
        private readonly IIssuerService _issuerService;
        private readonly IUrlService _urlService;
        private readonly IEmailService _emailService;
        private readonly ISettingsService _settingsService;

        private bool NotAllowedWithCurrentSegment(IEnumerable<ContentItemSegmentation> segments)
        {
            var isContentRestrictedToAnySegment = segments.Count() > 0;
            var isContentRestrictedToCurrenteSegment = segments.Any(s => CurrentSegmentationIds.Contains(s.SegmentationId));
            var isSegmentFilterOff = CurrentSegmentationIds.Any(s => s.Equals(RegionConfigManager.DefaultSegmentation, StringComparison.InvariantCultureIgnoreCase));
            return isContentRestrictedToAnySegment &&
                 !isContentRestrictedToCurrenteSegment &&
                 !isSegmentFilterOff;
        }

        public ContentDetailController(SlamContext slamContext, SlamContextService slamContextService, AssetRepository assetRepository, MigratedContentRepository migratedContentRepository, IContentItemService contentItemService, IUrlService urlService, IIssuerService issuerService, IRegionService regionService, IEmailService emailService, ISettingsService settingsService)
        {
            _slamContext = slamContext;
            _slamContextService = slamContextService;
            _assetRepository = assetRepository;
            _migratedContentRepository = migratedContentRepository;
            _contentItemService = contentItemService;
            _urlService = urlService;
            _issuerService = issuerService;
            _regionService = regionService;
            _emailService = emailService;
            _settingsService = settingsService;
        }

        private ContentItem CheckMigratedContentItem(string id)
        {
            var migratedContent = _migratedContentRepository.GetMigratedContent(id);
            if (migratedContent == null)
            {
                return null;
            }

            var contentItem = _slamContext.CreateQuery().FilterContentItemId(migratedContent.Id).Get().FirstOrDefault();
            return contentItem;
        }

        public ActionResult MigratedContent(string globalid)
        {
            var contentItem = CheckMigratedContentItem(globalid);
            if (contentItem == null)
            {
                throw new NotFoundException();
            }

            return Redirect($"~/{contentItem.FrontEndUrl.TrimStart('/')}");
        }

        [HttpGet]
        public ActionResult Asset(string contentItemId, string title, string trackingType = null)
        {
            return ProcessContentItem(contentItemId, trackingType);
        }

        [HttpPost]
        public ActionResult Asset(string contentItemId, string command, int? quantity)
        {
            var contentItem = _slamContext.CreateQuery().FilterContentItemId(contentItemId).IncludeSegmentations().Get().FirstOrDefault();
            if (contentItem == null)
            {
                throw new NotFoundException();
            }

            var segments = _contentItemService.GetSegmentation(contentItem.ContentItemId);

            if (NotAllowedWithCurrentSegment(segments))
            {
                throw new AuthorizationException();
            }

            var orderableAsset = _contentItemService.GetOrderableAsset(contentItem.ContentItemId);
            if (!string.IsNullOrWhiteSpace(orderableAsset.RestrictToSpecialAudience))
            {
                if (!string.IsNullOrWhiteSpace(CurrentSpecialAudience))
                {
                    string[] stringSeparators = new string[] { ";#" };
                    var orderableAssetSpecialAudiences = orderableAsset.RestrictToSpecialAudience.ToLowerInvariant().Split(stringSeparators, StringSplitOptions.RemoveEmptyEntries);
                    var currentSpecialAudiences = CurrentSpecialAudience.ToLowerInvariant().Split(stringSeparators, StringSplitOptions.RemoveEmptyEntries);

                    bool match = false;
                    foreach (var specAud in currentSpecialAudiences)
                    {
                        if (orderableAssetSpecialAudiences.Contains(specAud))
                        {
                            match = true;
                            break;
                        }
                    }

                    if (!match)
                    {
                        throw new AuthorizationException();
                    }
                }
                else
                {
                    throw new AuthorizationException();
                }
            }

            var model = ProcessOrderableAsset(orderableAsset, contentItem);
            model.Quantity = quantity;
            var addedToCart = false;
            switch (command)
            {
                case CommandElectronicDelivery:
                    addedToCart = ProcessElectronicDelivery(model);
                    break;
                case CommandPrintOnDemand:
                    addedToCart = ProcessPrintOnDemand(model, quantity);
                    break;
                case CommandBatchPrint:
                    addedToCart = ProcessBatchPrint(model, quantity);
                    break;
            }

            if (addedToCart)
                return Redirect("/portal/shoppingcart");

            return View("OrderableAsset", model);
        }

        public ActionResult ApplicableMarkets(string contentItemId)
        {
            var dbContext = DependencyResolver.Current.GetService<MarketingCenterDbContext>();
            var contentItemTags = dbContext.Tags.Where(t => t.ContentItems.Any(ci => ci.ContentItemId.Equals(contentItemId, StringComparison.OrdinalIgnoreCase))).Select(t => t.TagID);
            var regionId = UserContext.SelectedRegion;
            if (string.IsNullOrEmpty(regionId))
            {
                return null;
            }

            var region = _regionService.GetById(regionId);
            var node = _slamContext.GetTagTree()
                                   .FindNode(t => (t?.Tag?.TagId != null && (t?.Tag?.TagId?.Equals(region.TagId, StringComparison.OrdinalIgnoreCase) ?? false)) &&
                                                  (t.Parent?.TagCategory != null &&
                                                  (t.Parent?.TagCategory?.TagCategoryId?.Equals(MarketingCenterDbConstants.TagCategories.Markets, StringComparison.OrdinalIgnoreCase) ?? false)));

            var allregionMarkets = node.Children;
            if (allregionMarkets.Count < 2)
            {
                return new EmptyResult();
            }

            var regionMarkets = allregionMarkets.Where(cit => contentItemTags.Contains(cit.Parent.Tag.TagId) ||
                                                              contentItemTags.Contains(cit.Tag.TagId))
                                                .ForEach(rm => rm.Tag.Translate(UserContext.SelectedLanguage));

            var excludedregionMarkets = allregionMarkets.Where(cit => !(contentItemTags.Contains(cit.Parent.Tag.TagId)) &&
                                                                      (!contentItemTags.Contains(cit.Tag.TagId)))
                                                        .ForEach(rm => rm.Tag.Translate(UserContext.SelectedLanguage));

            var applicable = new List<string>();
            regionMarkets.ForEach((rm) =>
            {
                applicable.Add("\"" + rm.Tag.DisplayName + "\"");
            });
            var excluded = new List<string>();
            excludedregionMarkets.ForEach((rm) =>
            {
                excluded.Add("\"" + rm.Tag.DisplayName + "\"");
            });

            ViewData["CountriesTotal"] = allregionMarkets.Count;
            ViewData["AvailableInCountry"] = (regionMarkets.Any(rm => rm.Identifier.Equals(UserContext.User.Country.Trim(), StringComparison.Ordinal)) ?
                                              Resources.Forms.AvailableInCountry :
                                              Resources.Forms.NotAvailableInCountry);

site/Mastercard.MarketingCenter.Web/Controllers/FileController.cs
using Mastercard.MarketingCenter.Common.Extensions;
using Mastercard.MarketingCenter.Data.DTOs;
using Mastercard.MarketingCenter.Services.Interfaces;
using Mastercard.MarketingCenter.Web.Core.Filters;
using Slam.Cms.Data;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace Mastercard.MarketingCenter.Web.Controllers
{
    public class FileController : AsyncController
    {
        private readonly SlamContext _slamContext;
        private readonly ISettingsService _settingsService;
        private readonly IImageService _imageService;

        public FileController(SlamContext slamContext, ISettingsService settingsService, IImageService imageService)
        {
            _slamContext = slamContext;
            _settingsService = settingsService;
            _imageService = imageService;
        }

        [PageTracking]
        public ActionResult HtmlDownload(string id, string title)
        {
            var htmlDownload = _slamContext.CreateQuery().FilterContentItemId(id).Get<HtmlDownloadDTO>().FirstOrDefault();
            if (htmlDownload == null)
            {
                Pulsus.LogManager.EventFactory.Create()
                                              .Text($"The HtmlDownload with ID: {id} and Title: {title} does not exist")
                                              .Push();

                return HttpNotFound();
            }

            var filename = htmlDownload.Filename;
            var filesPath = _settingsService.GetFilesFolder();
            var fullFilePath = Path.Combine(Server.MapPath(filesPath), filename.TrimStart('/').TrimStart('\\'));
            if (!System.IO.File.Exists(fullFilePath))
            {
                Pulsus.LogManager.EventFactory.Create()
                                              .Text($"The HtmlDownload File: {fullFilePath} is not valid!")
                                              .Push();

                return HttpNotFound();
            }

            Response.AppendHeader("Content-Disposition", $"inline; filename={Path.GetFileName(filename)}");
            return File(fullFilePath, filename.GetMimeType());
        }

        public ActionResult ProofFile(string file)
        {
            if (string.IsNullOrEmpty(file))
            {
                return HttpNotFound();
            }

            var fullPath = Server.MapPath(file);
            if (System.IO.File.Exists(fullPath) && fullPath.StartsWith(Server.MapPath(_settingsService.GetCustomizationFilesUploadPath())))
            {
                return File(fullPath, "application/octet-stream", Path.GetFileName(fullPath));
            }

            return HttpNotFound($"{Resources.Errors.FileNotFound}: {fullPath}");
        }

        [PageTracking]
        public ActionResult Download(string url)
        {
            return InternalDownload(url);
        }

        [PageTracking]
        public ActionResult DownloadImage(string url, string title)
        {
            if (string.IsNullOrEmpty(url) || !url.IsValidImage())
            {
                return HttpNotFound();
            }

            if (url.IsAbsoluteUrl())
            {
                return File(_imageService.GetImageFromUrl(url), url.GetMimeType(), title.IsNullOrWhiteSpace() ? Path.GetFileName(url) : $"{title}{Path.GetExtension(url)}");
            }

            return File(_imageService.GetMappedImage(url, true), url.GetMimeType(), title.IsNullOrWhiteSpace() ? Path.GetFileName(url) : $"{title}{Path.GetExtension(url)}");
        }

        [PageTracking]
        public ActionResult LibraryDownload(string url)
        {
            return InternalDownload(url);
        }

        private ActionResult InternalDownload(string url)
        {
            if (string.IsNullOrEmpty(url))
            {
                return HttpNotFound();
            }

            if (url.IsAbsoluteUrl() && url.IsValidImage())
            {
                string imagePath = _imageService.GetImageFromUrl(url);
                return File(imagePath, imagePath.GetMimeType(), Path.GetFileName(imagePath));
            }

            var filesPath = Server.MapPath(_settingsService.GetFilesFolder());
            var fullPath = Path.GetFullPath(Path.Combine(filesPath, url.TrimStart('/').TrimStart('\\')));
            if (System.IO.File.Exists(fullPath) && fullPath.StartsWith(filesPath))
            {
                return File(fullPath, "application/octet-stream", Path.GetFileName(url));
            }

            return HttpNotFound($"{Resources.Errors.FileNotFound}: {fullPath}");
        }
    }
}

site/Mastercard.MarketingCenter.Web/Views/ContentDetail/Asset.cshtml
@using Mastercard.MarketingCenter.Common.Extensions
@model AssetViewModel
@section Title {
    @Model.Title.StripHtml()
}

@section sectionHead {
    <script src="/portal/content/themes/orange/libs/jquery-ui.dialog.min.js" language=javascript type="text/javascript"></script>
}

@section Breadcrumb{
    @{
        var node = new SitemapNode() { Key = Model.ContentItemId, Title = Model.Title, Url = Model.FrontEndUrl };
    }
    @Html.Breadcrumb("tagbrowser", new List<SitemapNode>() { node }, node)

    @if (Model.EnableFavoriting)
    {
        Html.RenderAction("Subscription", "Profile", new { contentItemId = Model.ContentItemId });
    }
}

<!-- Asset -->
<header class="header-section header-first-section cold-colors content-spaces-in tac">
    <div class="inner">
        <h1>@Html.RawWithSnippets(Model.Title)</h1>
        @Html.RawWithSnippets(Model.ShortDescription)
    </div>
</header>

@Html.Partial("RegionsApplicableToClone", Model.RegionsApplicableToClone)

@Html.Partial("BackLink")

<div class="content-container content-spaces-in">
    <div class="content-text">
        <div class="row">
            <div class="col-sm-8">
                <article>
                    @Html.Action("ApplicableMarkets", "ContentDetail", new { contentITemId = Model.ContentItemId })
                    @if (Model.RelatedProgram != null)
                    {
                        <a href="@Model.RelatedProgram.AsContentItemListItem().ResourceUrl">@Model.RelatedProgram.Title</a>
                    }
                    @Html.RawWithSnippets(Model.LongDescription)
                    @if (Model.RelatedProgram != null)
                    {
                        @Html.Partial("RelatedProgramInner", new RelatedProgram() { ContentItemListItem = Model.RelatedProgram.AsContentItemListItem() })
                    }
                </article>
                <div class="col-sm-12">
                    @Html.DisplayFor(m => m.RelatedContentItemsList)
                    @{ Html.RenderAction("BrowseAllMaterialTag", "ContentDetail", new { tags = Model.BrowseAllMaterialTags }); }
                </div>
            </div>
            <aside class="col-sm-4">                
                <div class="col-sm-11 col-sm-offset-1">
                    @{ Html.RenderAction("AttachmentsAndCallToAction", "ContentDetail", new { attachments = Model.Attachments, callToAction = Model.CallToAction, mainImage = Model.MainImage, previewFiles = Model.PreviewFiles }); }
                </div>
            </aside>
        </div>
    </div>
</div>
<br />
<section class="page-section boxes-section cold-colors content-spaces-in invisible" id="related-content-boxes">
    <h1 class="section-header">@Resources.Shared.RelatedContent</h1>
    <div class="boxes-slider bigger buttoned">
        @Html.DisplayFor(m => m.InsightsCrossSellBox)
        @Html.DisplayFor(m => m.ProductsCrossSellBox)
        @Html.DisplayFor(m => m.MarketingCrossSellBox)
        @Html.DisplayFor(m => m.SolutionsCrossSellBox)
        @Html.DisplayFor(m => m.SegmentsCrossSellBox)
        @Html.DisplayFor(m => m.SafetySecurityCrossSellBox)
    </div>
</section>

site/Mastercard.MarketingCenter.Web/Views/ContentDetail/AttachmentsAndCallToAction.cshtml
@using Mastercard.MarketingCenter.Common
@model AttachmentsAndCallToActionViewModel

@if (Model.Attachments.Count() > 0 || !string.IsNullOrEmpty(Model.CallToAction.StripHtml()) || !string.IsNullOrEmpty(Model.MainImage))
{
    <dl class="aside-panel reset">
        <dt>@Resources.Shared.LearnMore</dt>
        @if (!string.IsNullOrEmpty(Model.MainImage))
        {
            <dd>
                @Html.AssetMainImage(Model.MainImage, "img-responsive")
            </dd>
        }
        @if (Model.Attachments.Any())
        {
            <dd>
                <p><strong>@Resources.Shared.DownloadAndReview:</strong></p>
                <ul class="files-list reset">
                    @foreach (var attachment in Model.Attachments)
                    {
                        <li class="break-all">
                            @if (Model.PreviewFiles)
                            {
                                @Html.Partial("PreviewFile", Html.GetAttachmentPreviewFile(attachment))
                            }
                            else
                            {
                                @Html.Partial("Attachment", attachment)
                            }
                        </li>
                    }
                </ul>
            </dd>
        }
        @if (!string.IsNullOrEmpty(Model.CallToAction.StripHtml()))
        {
            <dd>
                @Html.RawWithSnippets(Model.CallToAction)
            </dd>
        }
    </dl>
}

site/Mastercard.MarketingCenter.Web/Views/ContentDetail/BrowseAllMaterialTag.cshtml
@model BrowseAllMaterialViewModel

@if (Model.Render)
{
    <div class="block-more-related-materials">
        <a href="@Model.Url">@Resources.Shared.BrowseRelatedMaterials (@Model.Count)</a>
    </div>
}

site/Mastercard.MarketingCenter.Web/Views/ContentDetail/OrderableAsset.cshtml
@using Mastercard.MarketingCenter.Common.Extensions
@model OrderableAssetViewModel
@section Title {
    @Model.Title.StripHtml()
}
@section Breadcrumb{
    @{
        var node = new SitemapNode() { Key = Model.ContentItemId, Title = Model.Title, Url = Model.FrontEndUrl };
    }
    @Html.Breadcrumb("tagbrowser", new List<SitemapNode>() { node }, node)

    @if (Model.EnableFavoriting)
    {
        Html.RenderAction("Subscription", "Profile", new { contentItemId = Model.ContentItemId });
    }
}

<!-- Orderable Asset -->
@if (Model.RelatedProgram != null)
{
    <header class="header-section header-first-section cold-colors content-spaces-in tac">
        <div class="inner">
            <h1>@Html.RawWithSnippets(Model.RelatedProgram.Title)</h1>
            @Html.RawWithSnippets(Model.RelatedProgram.ShortDescription)
            <p><a href="@Model.RelatedProgram.AsContentItemListItem().ResourceUrl"><strong>@Resources.Shared.LearnMore</strong></a></p>
        </div>
    </header>
}
<section class="header-section header-second-section content-spaces-in hottest-colors">
    <div class="row tac">
        <h2 class="col-lg-8 col-lg-offset-2">@Html.RawWithSnippets(Model.Title)<br /><span class="p3">SKU# @Model.Sku</span></h2>
        <div class="col-lg-8 col-lg-offset-2" style="font-weight: 100;">
            @Html.RawWithSnippets(Model.LongDescription)
            @if (Model.Vdp.HasValue && Model.Vdp.Value)
            {
                <h3>@Resources.ShoppingCart.VariableDataPrinting</h3>
                <p>@Resources.ShoppingCart.VariableDataPrintingDescription</p>
            }
            <input type="hidden" name="contentItemId" value="@Model.ContentItemId" />
            @if (!string.IsNullOrEmpty(Model.CallToAction) && Model.CallToAction != "<p><br></p>")
            {
                @Html.Raw(Model.CallToAction)
            }
        </div>
    </div>
</section>
@* Errors *@
@if (!string.IsNullOrEmpty(Model.ElectronicDeliveryError) || !string.IsNullOrEmpty(Model.PrintOnDemandError) || !string.IsNullOrEmpty(Model.BatchPrintError))
{
    <div class="content-container content-spaces-in spaces-vertical-in">
        <div class="row">
            <div class="col-md-10">
                <ul class="alert-warning h4 reset">
                    @if (!string.IsNullOrEmpty(Model.ElectronicDeliveryError))
                    {
                        <li>@Html.Raw(Model.ElectronicDeliveryError)</li>
                    }
                    @if (!string.IsNullOrEmpty(Model.PrintOnDemandError))
                    {
                        <li>@Html.Raw(Model.PrintOnDemandError)</li>
                    }
                    @if (!string.IsNullOrEmpty(Model.BatchPrintError))
                    {
                        <li>@Html.Raw(Model.BatchPrintError)</li>
                    }
                </ul>
            </div>
        </div>
    </div>
}
<div class="page-section slides-section">
    <div class="tiles-carousel cold">
        <section class="tiles-slider learn-more-tiles" data-slick="">
            <div style="background-color: #f4f4f4;">
                <div class="inner-text inner-half">
                    <h2>@Resources.Shared.LearnMore</h2>
                    <div class="img">@Html.AssetInBoxMainImage(Model.MainImage, "img-responsive")</div>
                    <div class="txt">
                        @if (!string.IsNullOrEmpty(Model.PDFPreview))
                        {
                            <p>@Resources.ShoppingCart.SampleCreativeDescription</p>
                            <a href="@Url.Action("LibraryDownload", "File", new { url = Model.PDFPreview })" target="_blank" class="btn">@Resources.ShoppingCart.SampleCreative</a>
                        }
                    </div>
                </div>
            </div>
        </section>
        <section>
            <ul class="x4 icon-tiles">
                @if (!string.IsNullOrEmpty(Model.ElectronicDeliveryFile) && Model.PricingSchedule.DownloadPrice.HasValue && !Model.Archived)
                {
                    <li class="cell" style="background-color: #e1e1e1;">
                        <div class="inner-text">
                            @Resources.ShoppingCart.OrderForElectronicDelivery
                        </div>
                    </li>
                    <li class="cell" style="background-color: #ebebeb;">
                        <div class="inner-text inner-act">
                            <strong>@Resources.ShoppingCart.Price: @Model.PricingSchedule.DownloadPrice.Value.ToString("C")</strong>
                            @using (Html.BeginForm("Asset", "ContentDetail", FormMethod.Post, new { name = "electronicdelivery" }))
                            {
                                <input type="hidden" name="command" value="electronicdelivery" />
                                <button data-form-name="electronicdelivery" class="btn btn-prompt" data-prompt="@Resources.ShoppingCart.CompleteCheckoutLabel">@Resources.Shared.Download</button>
                            }
                        </div>
                    </li>
                }
                @if (!string.IsNullOrEmpty(Model.PricingSchedule.PricingTable) && !Model.PricingSchedule.UnitPrice.HasValue && !Model.Archived)
                {
                    <li class="cell" style="background-color: #d7d7d7;">
                        <div class="inner-text">
                            @Resources.ShoppingCart.OrderPrintedMaterials
                            <a id="pricing-table-anchor" href="#">@Resources.ShoppingCart.ReviewPricing</a>
                        </div>
                    </li>
                    <li class="cell" style="background-color: #e1e1e1;">
                        <div class="inner-text inner-act">
                            @using (Html.BeginForm("Asset", "ContentDetail", FormMethod.Post, new { name = "printondemmand" }))
                            {
                                <strong class="qty-lbl">@Resources.ShoppingCart.QTY:&nbsp;</strong>
                                <span class="qty-control"><input class="form-control" type="number" name="quantity" maxlength="6" /></span>
                                <input type="hidden" name="command" value="printondemmand" />
                                <button data-form-name="printondemmand" class="btn btn-prompt" data-prompt="@Resources.ShoppingCart.CompleteCheckoutLabel">@Resources.ShoppingCart.AddToCart</button>
                            }
                        </div>
                    </li>
                }
                else if (Model.PricingSchedule.UnitPrice.HasValue && !string.IsNullOrEmpty(Model.PricingSchedule.UnitSize) && !Model.Archived)
                {
                    <li class="cell" style="background-color: #cccccc;">
                        <div class="inner-text">
                            @((!string.IsNullOrEmpty(Model.PricingSchedule.TableHeader)) ? Model.PricingSchedule.TableHeader : Resources.ShoppingCart.BatchPrinting)
                            <div class="inner-box">
                                <strong>@Resources.ShoppingCart.UnitSize: </strong>@Model.PricingSchedule.UnitSize<br />
                                <strong>@Resources.ShoppingCart.UnitPrice: </strong>@Model.PricingSchedule.UnitPrice.Value.ToString("C")
                            </div>
                        </div>
                    </li>
                    <li class="cell" style="background-color: #d7d7d7;">
                        <div class="inner-text">
                            @using (Html.BeginForm("Asset", "ContentDetail", FormMethod.Post, new { name = "batchprint" }))
                            {
                                <strong class="qty-lbl">@Resources.ShoppingCart.QTY:&nbsp;</strong>
                                <span class="qty-control">
                                    <input type="number" class="form-control" name="quantity" MaxLength="6" value="@Model.Quantity" />
                                </span>
                                <input type="hidden" name="command" value="batchprint" />
                                <button data-form-name="batchprint" class="btn btn-prompt" data-prompt="@Resources.ShoppingCart.CompleteCheckoutLabel">@Resources.ShoppingCart.AddToCart</button>
                            }
                        </div>
                    </li>
                }
            </ul>
        </section>
    </div>
</div>
@if (Model.RelatedProgram != null)
{
    @Html.Partial("RelatedProgram", new RelatedProgram() { ContentItemListItem = Model.RelatedProgram.AsContentItemListItem() })
}
@Html.DisplayFor(m => m.RelatedContentItemsList)
<section class="page-section boxes-section content-spaces-in invisible" id="related-content-boxes">
    <h1 class="section-header">@Resources.Shared.RelatedContent</h1>
    <div class="boxes-slider bigger buttoned">
        @Html.DisplayFor(m => m.InsightsCrossSellBox)
        @Html.DisplayFor(m => m.ProductsCrossSellBox)
        @Html.DisplayFor(m => m.MarketingCrossSellBox)
        @Html.DisplayFor(m => m.SolutionsCrossSellBox)
    </div>
</section>
@{ Html.RenderAction("PricingTable", "ContentDetail", new { pricingSchedule = Model.PricingSchedule }); }
<script type="text/javascript">
    $(function () {

        function dialogPos() {
            var $dialog = $('.ui-dialog:visible');
            $dialog.css({
                'position': ($dialog.height() < $(window).height() ? 'fixed' : 'absolute')
            });
            if ($(window).width() > 767) {
                $dialog.css({
                    'top': ($(window).height() > $dialog.height() ? '50%' : '10%'),
                    'left': '50%',
                    'marginLeft': 0 - ($dialog.width() / 2),
                    'marginTop': 0 - ($(window).height() > $dialog.height() ? ($dialog.height() / 2) : 0)
                });
            }
            else {
                $dialog.css({
                    'position': 'absolute',
                    'left': 0,
                    'marginLeft': 0
                });
            }
        }

        $("#dialog-modal").dialog({
            open: function () {
                dialogPos();
                $(window).on('resize', dialogPos);
            }
        });

        $("#pricing-table-anchor").click(function (e) {
            e.preventDefault();
            $("#dialog-modal").dialog('open');
        });

        $('[data-form-name]').on('click', function (e) {
            var $form = $('[name="' + $(this).data('form-name') + '"]'),
                url = $form.attr('action');
            if ($('.is-mobile').length) {
                $.ajax({
                    type: "POST",

                    url: url,
                    data: $form.serialize(), // serializes the form's elements.
                    success: function (data) {
                        if (window.console) console.log('form submit:', data); // show response from the php script.
                    }
                });

                e.preventDefault();
            } else {
                $form.submit();
            }
        });
    });
    $(function () {
        $(".submit").on("click", function () {
            $("form").submit();
        });

        $("input[name^='quantity']").on("keydown", function () {
            if ($(this).val().length >= parseInt($(this).attr("MaxLength"))) {
                $(this).val($(this).val().substring(0, parseInt($(this).attr("MaxLength")) - 1));
            }
        });
    }
    );
</script>