site/Mastercard.MarketingCenter.Cms/Models/ContentType/ContentTypeModel.cs
using System.ComponentModel.DataAnnotations;

namespace Mastercard.MarketingCenter.Cms.Models
{
    public class ContentTypeModel
    {
        public string ContentTypeId { get; set; }

        [Required]
        public string Title { get; set; }
    }
}

site/Mastercard.MarketingCenter.Cms/Controllers/ContentTypeController.cs
using Mastercard.MarketingCenter.Cms.Core.ActionFilters;
using Mastercard.MarketingCenter.Cms.Models;
using Mastercard.MarketingCenter.Cms.Services.Services;
using Mastercard.MarketingCenter.Common.Services;
using Mastercard.MarketingCenter.Data.Daos;
using Mastercard.MarketingCenter.Data.Entities;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Mastercard.MarketingCenter.Cms.Controllers
{
    [CustomAuthorize]
    public class ContentTypeController : CmsBaseController
    {
        private readonly ContentTypeDao _contentTypeDao;
        private readonly ContentTypeService _contentTypeService;
        private readonly IdGeneratorService _idGeneratorService;

        public ContentTypeController(ContentTypeDao contentTypeDao, ContentTypeService contentTypeService, IdGeneratorService idGeneratorService)
        {
            _contentTypeDao = contentTypeDao;
            _contentTypeService = contentTypeService;
            _idGeneratorService = idGeneratorService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult GetContentTypes()
        {
            var contentTypes = _contentTypeDao.GetAll().ToList();
            return Json(new { data = contentTypes, recordsTotal = contentTypes.Count(), recordsFiltered = contentTypes.Count }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [UnitOfWork]
        public ActionResult Create(ContentTypeModel model)
        {
            if (ModelState.IsValid)
            {
                var tableName = model.Title.Replace(" ", string.Empty);
                var newContentType = new ContentType
                {
                    ContentTypeId = _idGeneratorService.GetNewUniqueId(),
                    Title = model.Title,
                    DefaultIcon = "blank.jpg",
                    TableName = tableName
                };

                _contentTypeDao.Add(newContentType);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        [UnitOfWork]
        public ActionResult Update(ContentTypeModel model)
        {
            if (ModelState.IsValid)
            {
                var contentType = _contentTypeDao.GetById(model.ContentTypeId);
                contentType.Title = model.Title;

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Update(string id)
        {
            var contentType = _contentTypeDao.GetById(id);
            var model = new ContentTypeModel { ContentTypeId = contentType.ContentTypeId, Title = contentType.Title };

            return View(model);
        }

        [HttpPost]
        [UnitOfWork]
        public ActionResult Delete(string id)
        {
            try
            {
                _contentTypeService.DeleteContentType(id);
                return Json(new { Ok = true }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                return Json(new { Ok = false, ex.Message });
            }
        }
    }
}

site/Mastercard.MarketingCenter.Cms/Views/ContentType/Create.cshtml
@model ContentTypeModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section HeaderTitle
{
    Create new Content Type
}

<div class="ibox-content">

    @Html.Partial("_ErrorAlert")

    @using (Html.BeginForm("Create", "ContentType", FormMethod.Post, new { @class = "form-horizontal" }))
    {

        @Html.Partial("_ContentTypeForm", Model)

        <hr />

        <div class="form-group">
            <div class="col-sm-4 col-sm-offset-2">
                @Html.ActionLink("Cancel", "Index", "ContentType", null, new { @class = "btn btn-white" })
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </div>
    }

</div>

site/Mastercard.MarketingCenter.Cms/Views/ContentType/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section head
{
    @System.Web.Optimization.Styles.Render("~/Content/plugins/datatables")
    @System.Web.Optimization.Scripts.Render("~/bundles/datatables")
    @System.Web.Optimization.Scripts.Render("~/bundles/contenttype")
}

@section HeaderTitle
{
    Content Types
}

<div class="ibox-content">

    <a href="@Url.Action("Create", "ContentType")" class="btn btn-primary"><em class="fa fa-plus"></em>&nbsp;&nbsp;Add new item</a>
    <hr />
    <table class="table table-hover" id="contenTypesGrid">
        <thead>
            <tr>
                <th scope="col">Edit</th>
                <th scope="col">Title</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

@section scripts
{
    <script>
        var contentType = new ContentType("@Url.Action("GetContentTypes", "ContentType")", "@Url.Action("Update", "ContentType")");
        contentType.initialize();
    </script>
}

site/Mastercard.MarketingCenter.Cms/Views/ContentType/Update.cshtml
@model ContentTypeModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section head
{
    @System.Web.Optimization.Scripts.Render("~/bundles/contenttype")
}

@section HeaderTitle
{
    Update @Model.Title
}

<div class="ibox-content">

    @Html.Partial("_ErrorAlert")
    <div id="errors" class="alert alert-danger" role="alert"></div>

    @using (Html.BeginForm("Update", "ContentType", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.HiddenFor(o => o.ContentTypeId)

        @Html.Partial("_ContentTypeForm", Model)

        <hr />
        
        <div class="form-group">
            <div class="col-sm-4 col-sm-offset-1">
                @Html.ActionLink("Cancel", "Index", "ContentType", null, new { @class = "btn btn-white" })
                <button class="btn btn-primary" type="submit">Update</button>
            </div>
            <div class="col-sm-1 col-sm-offset-4">
                <button id="delete" class="btn btn-primary">Delete Content Type</button>
            </div>
        </div>
    }
</div>

@section scripts
{
    <script>
        var contentTypeUpdate = new ContentTypeUpdate("@Url.Action("Delete", "ContentType", new { id = Model.ContentTypeId })", "@Url.Action("Index", "ContentType")");
        contentTypeUpdate.initialize();
    </script>
}

site/Mastercard.MarketingCenter.Cms/Views/ContentType/_ContentTypeForm.cshtml
@model ContentTypeModel

@using (Html.BeginFormGroup(o => o.Title))
{
    <div class="form-group">
        <label class="col-sm-2 control-label">Title *</label>

        <div class="col-sm-10">@Html.TextBoxFor(o => o.Title, new { @class = "form-control" })</div>
    </div>
}